server:
  port: 8000
  servlet:
    context-path: /

spring:
  profiles:
    active: prod

coolsms:
  url : https://api.coolsms.co.kr
  api-key: NCS4JRJYDE5VQXFF
  api-secret: NIZTMQIUULKHTBSD9XCSZ027QFAJMRS8
  sender-phone: 01093701938
